version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: polyglot
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    environment:
      - PORT=4100
    depends_on:
      - redis
    ports:
      - "4100:4100"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/polyglot
      - JWT_DEV_SECRET=dev-secret
      - PROXY_HOST=proxy
      - PROXY_PORT=4100
    depends_on:
      - db
      - proxy
    ports:
      - "4000:4000"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - "3000:3000"

volumes:
  db_data:
