
services:
  db:
    image: postgres:15-alpine
    container_name: polyglot_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: polyglot
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: polyglot_redis
    restart: unless-stopped
    ports: ["6379:6379"]
volumes:
  db_data:
