name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install & lint (use pnpm)
      run: |
        corepack enable
        pnpm install --frozen-lockfile
        pnpm -w exec eslint "**/*.{js,jsx,mjs}" || true
        # keep npm tasks for legacy targets if present
        npm ci
        npx grunt
