name:

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true

    - name: Show lockfile head
      run: |
        echo "--- pnpm-lock.yaml head (for debugging) ---"
        sed -n '1,140p' pnpm-lock.yaml || true

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install & lint (use pnpm)
      run: |
        corepack enable
        pnpm install --frozen-lockfile
        pnpm -w exec eslint "**/*.{js,jsx,mjs}" || true

    - name: Run legacy npm tasks if present
      run: |
        if [ -f package-lock.json ]; then
          echo "package-lock.json found: running npm ci && npx grunt"
          npm ci
          npx grunt
        else
          echo "No package-lock.json: skipping legacy npm tasks"
        fi
